[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ideas_marketplace = "2dbLm1MoHidv2qSNAJRgyeC9jggBPvAX7GiwDNvqGsaR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://api.devnet.solana.com/"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
