[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ideas_marketplace = "svvdP8aiFfFhP2HhWKkLtvvqEKaGQ3rgcvN567v3gRf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899/"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
