[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ideas_marketplace = "BFGLMCzCmCyMPc2ntisKs7toR1N9u7kexi9zDyYbE5xo"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "http://localhost:8899/"
cluster = "https://api.devnet.solana.com"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dummy.ts"
