[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
ideas_marketplace = "9JSRe7vjdVgsuMk67b4fiBsxkxRD8Uy5eQQrTB64sYFQ"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "http://localhost:8899/"
cluster = "https://api.devnet.solana.com"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
